import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title:
    "Inito Fertility Monitor | Track Your Fertility Hormones At Home | Get Pregnant Faster",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://dqxth8lmt6m4r.cloudfront.net/assets/v1/favicon-dfde73a3fcff0eed6b58276a0e6b06e32d0f5bbeaaf601737e75ef393dfbd3c6.ico"
        />
      </head>
      <body className={montserrat.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
